# 🏃‍♀️ Continuous Integration and Delivery: Branch Testing
# ======================================================


---

name: 🔁 Branch integration testing


# Driving Event
# -------------
#
# What event starts this workflow: a push to ``main`` (or ``master`` in old
# parlance).

on:
    push:
        branches:
            -   '**'
            -   '!main'


# What to Do
# ----------
#
# Round up, yee-haw!

jobs:
    branch_testing:
        name: 🧩 Branch Testing
        runs-on: ubuntu-latest
        if: github.actor != 'pdsen-ci'

        strategy:
          matrix:
            java-version: [8, 11]

        steps:
          - uses: actions/checkout@v2
          - name: Set up OpenJDK
            uses: actions/setup-java@v2
            with:
              distribution: 'adopt'
              java-version: ${{ matrix.java-version }}

          - name: Test Software
            run: mvn compile test site --file pom.xml
            env:
               MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
               MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

# -*- mode: yaml; indent: 4; fill-column: 120; coding: utf-8 -*-
